apiVersion: v1
kind: Pod
metadata:
  name: garyhelloworld 
  namespace: hello
  labels:
     app: helloapp 
spec:
  containers:
    - name: helloappc
      image: 10.23.138.165:8082/gary/hello-image:0.4
      ports:
      - containerPort: 8080
        protocol: TCP
  imagePullSecrets:
    - name: garynexusin 
