# 创建一个可被外网访问的nginx应用
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hellodepc 
        image: 10.23.138.165:8082/gary/hello-image:0.4
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: garynexusin

