kind: Service
apiVersion: v1
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
  - protocol: TCP
    port:  8761
    targetPort: 8761
---
apiVersion: v1
kind: Pod
metadata:
  name: eureka
  labels:
     app: eureka
spec:
  containers:
    - name: eurekaservercontainer
      image: uhub.service.ucloud.cn/gary/gary-eureka-server:0.2
      ports:
      - containerPort: 8761
        protocol: TCP
      volumeMounts:
      - name: application-prop-vol
        mountPath: /etc/config
  volumes:
    - name: application-prop-vol
      configMap:
        name: application-properties
  imagePullSecrets:
    - name: garyuhub
