apiVersion: v1
kind: ReplicationController
metadata:
  name: rcprovider
spec:
  replicas: 2
  selector:
    app: rcprovider
  template:
    metadata:
      labels:
        app: rcprovider
    spec:
      containers:
        - image: 10.23.138.165:8082/gary/gary-eureka-provider:0.3
          name: rcproviderc
          ports:
          - containerPort: 8083
            protocol: TCP
          volumeMounts:
          - name: application-prop-vol
            mountPath: /etc/config
      volumes:
        - name: application-prop-vol
          configMap:
            name: application-properties
      imagePullSecrets:
        - name: garynexusin
