kind: Service
apiVersion: v1
metadata:
  name: zuul-service
spec:
  selector:
    app: zuul 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-deployment
  labels:
    app: zuul 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zuul 
  template:
    metadata:
      labels:
        app: zuul
    spec:
      containers:
      - name: zuuldepc 
        image: 10.23.138.165:8082/gary/gary-zuul-apigw:0.4
        ports:
        - containerPort: 8084
          protocol: TCP
        volumeMounts:
        - name: application-prop-vol
          mountPath: /etc/config
        - name: access-log
          mountPath: /accesslog
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.2.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: "10.23.247.155"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: "password"
        - name: ELASTIC_CLOUD_ID
          value:
        - name: ELASTIC_CLOUD_AUTH
          value:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #securityContext:
          #runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: access-log
          mountPath: /accesslog
          readOnly: true
      imagePullSecrets:
        - name: garynexusin
      volumes:
        - name: config
          configMap:
            defaultMode: 0644
            name: filebeat-config
        - name: application-prop-vol
          configMap:
            name: application-properties
        - name: access-log
          emptyDir: {}
